sudo: false
language: perl
addons:
  apt:
    packages:
      - build-essential
      - ikiwiki
      - libtext-multimarkdown-perl
      - libimage-magick-perl
install:
  - openssl aes-256-cbc -K $encrypted_03524223d143_key -iv $encrypted_03524223d143_iv -in .travisdeploykey.enc -out .travisdeploykey -d
  - chmod go-rwx .travisdeploykey
  - eval `ssh-agent -s`
  - ssh-add .travisdeploykey
  - git config --global push.default simple
  - git config --global user.name "Travis-CI"
  - git config --global user.email "noreply@travis-ci.org"
  - COMMIT_MESSAGE="Publishing site on `date "+%Y-%m-%d %H:%M:%S"` from
    `git log -n 1 --format='commit %h - %s'`"
script:
  #- set -e
  - export PERL5LIB="./.ikiwiki-plugin"
  - ikiwiki --rebuild --setup EntropyOrg.setup --url 'http://entropyorg.github.io/'
  - git clone --bare -b master git@github.com:EntropyOrg/EntropyOrg.github.io.git _site/.git
  - cd _site
  - git config core.bare false
  - git add -f .
  - 'git commit -m "${COMMIT_MESSAGE}" || true'
  - git push -f git@github.com:EntropyOrg/EntropyOrg.github.io.git master:master

branches:
  only:
    - source
